options:
  insert_models_over_bins: true
  belt_population_cycles: 5

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    products:
      part_0:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']

models_over_bins:
  bin3:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 4