options:
  insert_models_over_bins: true
  spawn_extra_models: false
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gear_part
    order_part3: disk_part
    order_part4: pulley_part

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv2]
    products:
      product_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 'pi']
      product_1:
        type: order_part3
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 'pi']
      product_2:
        type: order_part3
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      product_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]
  order_0_update_0:
    announcement_condition: wanted_products
    announcement_condition_value: 2
    shipment_count: 1
    destinations: [agv2]
    products:
      product_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      product_1:
        type: order_part3
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      product_2:
        type: order_part1
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 'pi']
      product_3:
        type: order_part4
        pose:
          xyz: [0.0, 0.0, 0]
          rpy: [0, 0, 0]
      product_4:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]

faulty_products:
  - piston_rod_part_47
  - piston_rod_part_35
  - gear_part_51

models_over_bins:
  bin1:
    models:
      pulley_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  bin2:
    models:
      disk_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.3, 0.47, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin3:
    models:
      gear_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.15, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 3
  bin5:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.35, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3
